import React, { useState } from "react";
import axios from "axios";

const ImageGenerator = () => {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");

  const handleGenerate = async () => {
    try {
      const response = await axios.post(
        "https://api.openai.com/v1/images/generations",
        {
          prompt: prompt,
          n: 1, // Number of images to generate
          size: "256x256", // Image size: '256x256', '512x512', or '1024x1024'
        },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.REACT_APP_OPEN_AI_KEY}`,
          },
        }
      );
      console.log("got response is", response);

      const image = response.data.data[0].url;
      setImageUrl(image);
    } catch (error) {
      console.error("Error generating image:", error);
    }
  };

  return (
    <div>
      <h1>OpenAI Image Generator</h1>
      <input
        type="text"
        placeholder="Enter your prompt"
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
      />
      <button onClick={handleGenerate}>Generate Image</button>
      {imageUrl && (
        <div>
          <h2>Generated Image:</h2>
          <img
            src={imageUrl}
            alt="Generated by OpenAI"
            style={{ maxWidth: "100%" }}
          />
        </div>
      )}
    </div>
  );
};

export default ImageGenerator;
